// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaoJWbwJk0Xi694ARHpdHhiNjT0SpASRs',
    appId: '1:930140433367:web:cf67bfa388fa517422b992',
    messagingSenderId: '930140433367',
    projectId: 'caltex-autopro-1e664',
    authDomain: 'caltex-autopro-1e664.firebaseapp.com',
    storageBucket: 'caltex-autopro-1e664.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo6mJdt0E4AyCHyd-d-N8mQtHDklDPLJk',
    appId: '1:930140433367:ios:32dcc67f189f112a22b992',
    messagingSenderId: '930140433367',
    projectId: 'caltex-autopro-1e664',
    storageBucket: 'caltex-autopro-1e664.firebasestorage.app',
    iosBundleId: 'com.example.automotiveMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaoJWbwJk0Xi694ARHpdHhiNjT0SpASRs',
    appId: '1:930140433367:web:2c9604ea695203e822b992',
    messagingSenderId: '930140433367',
    projectId: 'caltex-autopro-1e664',
    authDomain: 'caltex-autopro-1e664.firebaseapp.com',
    storageBucket: 'caltex-autopro-1e664.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo6mJdt0E4AyCHyd-d-N8mQtHDklDPLJk',
    appId: '1:930140433367:ios:32dcc67f189f112a22b992',
    messagingSenderId: '930140433367',
    projectId: 'caltex-autopro-1e664',
    storageBucket: 'caltex-autopro-1e664.firebasestorage.app',
    iosBundleId: 'com.example.automotiveMobile',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmssL8Aipf7I62gig5gToAQcQtLSu1UJI',
    appId: '1:930140433367:android:ce9c87496ef3d19b22b992',
    messagingSenderId: '930140433367',
    projectId: 'caltex-autopro-1e664',
    storageBucket: 'caltex-autopro-1e664.firebasestorage.app',
  );

}